query getProducts(
  $after: String
  $slug: [String]
  $first: Int = 100
  $orderby: [ProductsOrderbyInput] = { field: DATE, order: DESC }
) {
  products(
    first: $first
    after: $after
    where: {
      categoryIn: $slug
      typeNotIn: EXTERNAL
      visibility: VISIBLE
      minPrice: 0
      orderby: $orderby
    }
  ) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      databaseId
      slug
      name
      type: __typename

      image {
        sourceUrl(size: WOOCOMMERCE_THUMBNAIL)
        altText
      }

      productCategories(first: 3) {
        nodes {
          slug
          name
        }
      }

      ... on SimpleProduct {
        onSale
        price
        salePrice
        regularPrice
        averageRating
      }

      ... on VariableProduct {
        onSale
        price
        salePrice
        regularPrice
        averageRating
        variations(first: 100) {
          nodes {
            name
            databaseId
            price
            regularPrice
            salePrice
            slug
            stockQuantity
            stockStatus
            hasAttributes
            image {
              ...Image
              cartSourceUrl: sourceUrl(size: THUMBNAIL)
              producCardSourceUrl: sourceUrl(size: WOOCOMMERCE_THUMBNAIL)
            }
            attributes {
              nodes {
                ...VariationAttribute
              }
            }
          }
        }
      }

      ... on ExternalProduct {
        price
        averageRating
      }

      ... on GroupProduct {
        price
        averageRating
      }
    }
  }
}

fragment VariationAttribute on VariationAttribute {
  name
  attributeId
  value
  label
}
